batch_size: 128
data_root: /home/sicily/cv4e_cagedbird_ID/data
device: cuda
image_size:
- 224
- 224
learning_rate: 0.001
num_classes: 29
num_epochs: 200
num_workers: 4
seed: 32678456782
weight_decay: 0.001
