# Environment/computational parameters
seed: 32678456782       
device: cuda
num_workers: 4 

# Dataset parameters
data_root: /home/home01/bssbf/cv4e_cagedbird_ID/data2
num_classes: 56

# Training hyperparameters
image_size: [224, 224]
num_epochs: 100
batch_size: 128
learning_rate: 0.001
weight_decay: 0.001
scheduler_step_size: 5  # Update the learning rate every 5 epochs
scheduler_gamma: 0.5  # Reduce the learning rate by 50% each step

# Comet ML experiment saving details
experiment_name: ep100_56sp_lr_sched_step5_gamma0.5
project_name: cagedbird-classifier
api_key: 6D79SKeAIuSjteySwQwqx96nq
